# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainLoop.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#
#
#Project Title: Rock, Paper, Scissors Game Demo
#Project Developer: Peter Khuu
#Project Date Began: 09/21/2021
#Project Date Finish: 10/18/2021
#
#

from PyQt5 import QtCore, QtGui, QtWidgets
import random
import sys
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

class Ui_GameLoop(object):
    def __init__(self):
        super().__init__()
        
    def displayText(self,name,winCon):
        self.Player_Name = QtWidgets.QLabel()
        self.name=name
        self.win=winCon
        #print(f'{self.win}')
        self.rnum=1
        self.pnum=0
        self.cnum=0
           
    def game_play(self,user_choice):
        
        mylist=['Rock','Paper','Scissors']
        randChoice=random.choice(mylist)
        if user_choice=="Rock":
            self.Player_image.setPixmap(QtGui.QPixmap("photo\'s/leftRock.png"))
            if randChoice=="Paper":
                self.Computer_image.setPixmap(QtGui.QPixmap("photo\'s/rightPaper.png"))
                self.resultMessage.setText("Computer Won This Round!")
                print('Computer Win')
                self.Round.setText(f"Round: {self.rnum}")
                self.cnum+=1
                self.Computer_Name.setText(f"Computer: {self.cnum}")
                self.rnum+=1
            elif randChoice=="Scissors":
                self.Computer_image.setPixmap(QtGui.QPixmap("photo\'s/rightScissors.png"))
                self.Round.setText(f"Round: {self.rnum}")
                self.resultMessage.setText(f"{self.name} Won This Round!")
                print('player Win')
                self.pnum+=1
                self.Player_Name.setText(f"{self.name}: {self.pnum}")
                self.rnum+=1
            else:
                self.Computer_image.setPixmap(QtGui.QPixmap("photo\'s/rightRock.png"))
                self.resultMessage.setText("Draw!")
                print('Draw')
                self.Round.setText(f"Round: {self.rnum}")
                self.rnum+=1              
        elif user_choice=="Paper":
            self.Player_image.setPixmap(QtGui.QPixmap("photo\'s/leftPaper.png"))
            if randChoice=="Rock":
                self.Computer_image.setPixmap(QtGui.QPixmap("photo\'s/rightRock.png"))
                self.Round.setText(f"Round: {self.rnum}")
                self.resultMessage.setText(f"{self.name} Won This Round!")
                print('player Win')
                self.pnum+=1
                self.Player_Name.setText(f"{self.name}: {self.pnum}")
                self.rnum+=1
            elif randChoice=="Scissors":
                self.Computer_image.setPixmap(QtGui.QPixmap("photo\'s/rightScissors.png"))
                self.Round.setText(f"Round: {self.rnum}")
                self.resultMessage.setText("Computer Won This Round!")
                print('Computer Win')
                self.cnum+=1
                self.Computer_Name.setText(f"Computer: {self.cnum}")
                self.rnum+=1
            else:
                self.Computer_image.setPixmap(QtGui.QPixmap("photo\'s/rightPaper.png"))
                self.resultMessage.setText("Draw!")
                print('Draw')
                self.Round.setText(f"Round: {self.rnum}")
                self.rnum+=1     
        else:
            self.Player_image.setPixmap(QtGui.QPixmap("photo\'s/leftScissors.png"))
            if randChoice=="Rock":
                self.Computer_image.setPixmap(QtGui.QPixmap("photo\'s/rightRock.png"))
                self.Round.setText(f"Round: {self.rnum}")
                self.resultMessage.setText("Computer Won This Round!")
                print('Computer Win')
                self.cnum+=1
                self.Computer_Name.setText(f"Computer: {self.cnum}")
                self.rnum+=1
            elif randChoice=="Paper":
                self.Computer_image.setPixmap(QtGui.QPixmap("photo\'s/rightPaper.png"))
                self.Round.setText(f"Round: {self.rnum}")
                self.resultMessage.setText(f"{self.name} Won This Round!")
                print('player Win')
                self.pnum+=1
                self.Player_Name.setText(f"{self.name}: {self.pnum}")
                self.rnum+=1
            else:
                self.Computer_image.setPixmap(QtGui.QPixmap("photo\'s/rightScissors.png"))
                print('Draw')
                self.resultMessage.setText("Draw!")
                self.Round.setText(f"Round: {self.rnum}")
                self.rnum+=1

        if (self.pnum == self.win and self.pnum<=self.win) or (self.cnum==self.win and self.cnum<=self.win):
            self.rnum-=1
            msgBox = QMessageBox()
            msgBox.setIcon(QMessageBox.Information)
            if self.pnum == self.win and self.cnum < self.win:
                msgBox.setText(f"Congratulations!!!!!!!!!{self.name} Won!!!!!!!!\n Please click the reset button or quit button.")
            if self.cnum == self.win and self.pnum < self.win:
                msgBox.setText("Congratulations!!!!!!!!!Computer Won!!!!!!!!\n Please click the reset button or quit button.")  
            msgBox.setWindowTitle("QMessageBox Title")
            msgBox.setStandardButtons(QMessageBox.Ok)
            msgBox.buttonClicked.connect(self.msgButtonClick)

            returnValue = msgBox.exec()
            if returnValue == QMessageBox.Ok:
                print('OK clicked')
                self.RockButton.hide()
                self.PaperButton.hide()
                self.ScissorsButton.hide()

    def msgButtonClick(self):
        print("Message Button Was Clicked")                       
    def rock_click(self):
        self.game_play(user_choice='Rock')
    def paper_click(self):
        self.game_play(user_choice='Paper')
    def scissors_click(self):
        self.game_play(user_choice='Scissors')
    def reset_click(self):
        from UserMenu import Ui_MainWindow
        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.MainWindow)
        self.MainWindow.show()
    def quit_click(self):
        print('Quit button was click\nGame app is now ending')     
    def setupUi(self, GameLoop):
        GameLoop.setObjectName("GameLoop")
        GameLoop.resize(552, 426)
        self.centralwidget = QtWidgets.QWidget(GameLoop)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_4.addLayout(self.gridLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.RockButton = QtWidgets.QPushButton(self.centralwidget)
        self.RockButton.clicked.connect(self.rock_click)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RockButton.setFont(font)
        self.RockButton.setObjectName("RockButton")
        self.horizontalLayout_3.addWidget(self.RockButton)
        self.PaperButton = QtWidgets.QPushButton(self.centralwidget)
        self.PaperButton.clicked.connect(self.paper_click)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.PaperButton.setFont(font)
        self.PaperButton.setObjectName("PaperButton")
        self.horizontalLayout_3.addWidget(self.PaperButton)
        self.ScissorsButton = QtWidgets.QPushButton(self.centralwidget)
        self.ScissorsButton.clicked.connect(self.scissors_click)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ScissorsButton.setFont(font)
        self.ScissorsButton.setObjectName("ScissorsButton")
        self.horizontalLayout_3.addWidget(self.ScissorsButton)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_4.addLayout(self.gridLayout_7)
        self.gridLayout_8.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Player_Name = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Player_Name.setFont(font)
        self.Player_Name.setAlignment(QtCore.Qt.AlignCenter)
        self.Player_Name.setObjectName("Player_Name")
        self.gridLayout_4.addWidget(self.Player_Name, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Round = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Round.setFont(font)
        self.Round.setAlignment(QtCore.Qt.AlignCenter)
        self.Round.setObjectName("Round")
        self.gridLayout_2.addWidget(self.Round, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Computer_Name = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Computer_Name.setFont(font)
        self.Computer_Name.setAlignment(QtCore.Qt.AlignCenter)
        self.Computer_Name.setObjectName("Computer_Name")
        self.gridLayout.addWidget(self.Computer_Name, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout.addLayout(self.gridLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_8.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Player_image = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Player_image.setFont(font)
        self.Player_image.setFrameShape(QtWidgets.QFrame.Box)
        self.Player_image.setLineWidth(5)
        self.Player_image.setText("")
        self.Player_image.setPixmap(QtGui.QPixmap("photo\'s/defaultProfile.jpg"))
        self.Player_image.setScaledContents(False)
        self.Player_image.setAlignment(QtCore.Qt.AlignCenter)
        self.Player_image.setObjectName("Player_image")
        self.horizontalLayout_2.addWidget(self.Player_image)
        self.Computer_image = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Computer_image.setFont(font)
        self.Computer_image.setFrameShape(QtWidgets.QFrame.Box)
        self.Computer_image.setLineWidth(5)
        self.Computer_image.setText("")
        self.Computer_image.setPixmap(QtGui.QPixmap("photo\'s/computerProfile.png"))
        self.Computer_image.setScaledContents(False)
        self.Computer_image.setAlignment(QtCore.Qt.AlignCenter)
        self.Computer_image.setObjectName("Computer_image")
        self.horizontalLayout_2.addWidget(self.Computer_image)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.clicked.connect(self.reset_click)
        self.resetButton.clicked.connect(GameLoop.close)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.resetButton.setFont(font)
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_5.addWidget(self.resetButton)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalLayout_5.addLayout(self.gridLayout_11)
        self.resultMessage = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.resultMessage.setFont(font)
        self.resultMessage.setText("")
        self.resultMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.resultMessage.setWordWrap(True)
        self.resultMessage.setObjectName("resultMessage")
        self.horizontalLayout_5.addWidget(self.resultMessage)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.horizontalLayout_5.addLayout(self.gridLayout_12)
        self.quitButtion = QtWidgets.QPushButton(self.centralwidget)
        self.quitButtion.clicked.connect(self.quit_click)
        self.quitButtion.clicked.connect(GameLoop.close)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.quitButtion.setFont(font)
        self.quitButtion.setObjectName("quitButtion")
        self.horizontalLayout_5.addWidget(self.quitButtion)
        self.gridLayout_8.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        GameLoop.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GameLoop)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 552, 21))
        self.menubar.setObjectName("menubar")
        GameLoop.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GameLoop)
        self.statusbar.setObjectName("statusbar")
        GameLoop.setStatusBar(self.statusbar)

        self.retranslateUi(GameLoop)
        QtCore.QMetaObject.connectSlotsByName(GameLoop)

    def retranslateUi(self, GameLoop):
        _translate = QtCore.QCoreApplication.translate
        GameLoop.setWindowTitle(_translate("GameLoop", "MainWindow"))
        self.Player_Name.setText(_translate("GameLoop", f"{self.name}: {self.pnum}"))
        self.Round.setText(_translate("GameLoop", f"Round: {self.rnum}"))
        self.Computer_Name.setText(_translate("GameLoop", f"Computer: {self.cnum}"))
        self.RockButton.setText(_translate("GameLoop", "Rock"))
        self.PaperButton.setText(_translate("GameLoop", "Paper"))
        self.ScissorsButton.setText(_translate("GameLoop", "Scissors"))
        self.resetButton.setText(_translate("GameLoop", "Reset"))
        self.quitButtion.setText(_translate("GameLoop", "Quit"))

'''
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GameLoop = QtWidgets.QMainWindow()
    ui = Ui_GameLoop()
    ui.setupUi(GameLoop)
    GameLoop.show()
    sys.exit(app.exec_())
    '''
